ixNetworkApiServerIp: 192.168.28.10

# Below are for Linux API server only
username: hgee
password: IxiaIxia1234!
apiKey: None
deleteSession: False

forceTakePortOwnership: True
releasePorts: False
restPort: None
logLevel: info

ports:
  - name: Host1
    port: 192.168.28.5, 1, 1
    packetCapture:
      enable: True
      rxMode: captureAndMeasure
      controlPlane: False
      dataPlane: True
      sliceSize: 80

  - name: Host2
    port: 192.168.28.5, 1, 2
    packetCapture:
      enable: True
      rxMode: captureAndMeasure
      controlPlane: False
      dataPlane: True
      sliceSize: 80

topologies:
   - name: Host1
     ports:
       - Host1
     deviceGroups:
       - name: Host1
         multiplier: 1
         ethernet:
           name: Host1
         ipv4:
           name: Host1
           ipStartValue: 1.1.1.1
           ipStepValue: 0.0.0.0
           subnet: 255.255.255.0
           ipGatewayStartValue: 1.1.1.2
           ipGatewayStepValue: 0.0.0.0

   - name: Host2
     ports:
       - Host2
     deviceGroups:
       - name: Host2
         multiplier: 1
         ethernet:
           name: Host2
         ipv4:
           name: Host2
           ipStartValue: 1.1.1.2
           ipStepValue: 0.0.0.0
           subnet: 255.255.255.0
           ipGatewayStartValue: 1.1.1.1
           ipGatewayStepValue: 0.0.0.0
       

trafficItems:
  - name: Host1
    enable: True
    trafficType: raw
    srcPortName: Host1
    destPortName: Host2
    biDirection: True
    frameRate:
      type: percentLineRate
      rate: 50
    transmissionControl:
      # fixedFrameCount | continuous
      type: fixedFrameCount
      frameCount: 100
    frameSize: 128
    packetHeaders:
      ethernet:
        src:
          valueType: increment
          startValue: ngpfSrcMac
          stepValue: 00:00:00:00:00:00
          count: 1
        dst:
          valueType: increment
          startValue: ngpfResolvedGatewayMac
          stepValue: 00:00:00:00:00:01
          count: 1        
      ipv4:
        appendToStack: ethernet
        src:
          valueType: increment
          startValue: 1.1.1.1
          stepValue: 0.0.0.1
          count: 1
        dst:
          valueType: increment
          startValue: 1.1.1.2
          stepValue: 0.0.0.1
          count: 1
      udp:
        appendToStack: ipv4
        dstPort:
          startValue: 4791
        srcPort:
          startValue: 1111


  - name: Host2
    enable: True
    trafficType: raw
    srcPortName: Host2
    destPortName: Host1
    biDirection: True
    frameRate:
      type: percentLineRate
      rate: 50
    transmissionControl:
      # fixedFrameCount | continuous
      type: fixedFrameCount
      frameCount: 100
    frameSize: 128
    packetHeaders:
      ethernet:
        src:
          valueType: increment
          startValue: ngpfSrcMac
          stepValue: 00:00:00:00:00:00
          count: 1
        dst:
          valueType: increment
          startValue: ngpfResolvedGatewayMac
          stepValue: 00:00:00:00:00:01
          count: 1   
      ipv4:
        appendToStack: ethernet
        src:
          valueType: increment
          startValue: 2.2.2.1
          stepValue: 0.0.0.1
          count: 1
        dst:
          valueType: increment
          startValue: 2.2.2.2
          stepValue: 0.0.0.1
          count: 1
      udp:
        appendToStack: ipv4
        dstPort:
          startValue: 4791
        srcPort: 
          startValue: 1111





